# Generated by Django 2.1.1 on 2018-09-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180919_1405'),
        ('courses', '0002_auto_20180912_2148'),
    ]

    operations = [
    ]
