# Generated by Django 2.1.1 on 2018-09-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180913_1721'),
        ('users', '0004_auto_20180912_2148'),
    ]

    operations = [
    ]
